### ISSUE TITLE
Provide a way to define arbitrary archive types

### ISSUE THREAD

**Issue by itafroma** [itafroma/jekyll-archive#3]
Currently, JAG hard defines three archive "types": all posts filtered by day, all posts filtered by month, and all posts filtered by year. For each archive type, it also hard defines the path and title.

This configuration probably covers 80% of the use-cases for archives, but it'd be cool if there was some more flexibility. I mentioned in #1 for example that on my website, the default path pattern suits me (`YYYY/MM/DD`), but I wanted a different date pattern for the archive titles (`Month D, YYYY`).

I think it'll require a new configuration schema to do this properly. The current `archive` nested mapping will be replaced with a collection of sequences, which each sequence corresponding to an archive type. To give an example, the current hardcoded archive types would be defined like so:

```yaml
archive:
    - layout: archive
      path: /blog/:year/:month/:day
      title: Blog archive - :year/:month/:day
      exclude: ['projects']
    - layout: archive
      path: /blog/:year/:month
      title: Blog archive - :year/:month
      exclude: ['projects']
    - layout: archive
      path: /blog/:year
      title: Blog archive - :year
      exclude: ['projects']
```

(The top three could/should be pre-defined as defaults so you wouldn't have to type all that if you just want the 80% use case)

You could then customize each type however you'd like: want a different title, but just for the yearly archives? No problem!

Taking this one step farther, this new schema should allow for arbitrary collections of posts, not just all posts with a simple exclude filter. So `exclude` will become a nested mapping, with two keys—`categories` and `tags`—and will gain a complementary `include` nesting mapping with the same keys:

```yaml
archive:
    - layout: archive
      path: /blog/:year/:month/:day
      title: Blog archive - :year/:month/:day
      exclude:
          tags: ['hidden']
      include:
          categories: ['blog']
    - layout: archive
      path: /blog/:year/:month
      title: Blog archive - :year/:month
      exclude:
          tags: ['hidden']
      include:
          categories: ['blog']
    - layout: archive
      path: /blog/:year
      title: Blog archive - :year
      exclude:
          tags: ['hidden']
      include:
          categories: ['blog']
    - layout: archive
      path: /projects/:year
      title: Project archive - :year
      include:
          categories: ['projects']
```

The logic with the `include` and `exclude` keys would be the following:

- If `include` is missing, all posts will be included.
- If `include` is present, only posts matching the include criteria will be included.
- `exclude` is resolved after `include`.

For example, this would mean only posts in the `blog` category that do not have the `hidden` tag will be present in the archive type:

```yaml
include:
    categories: ['blog']
exclude:
    tags: ['hidden']
```

Open question: should the path and title keys only support Jekyll's permalink tokens? There's not a lot of flexibility with them, but they are what everyone knows. Alternatively, it'd be cool to just support whatever Ruby's [DateTime.strftime](http://www.ruby-doc.org/stdlib-1.9.3/libdoc/date/rdoc/DateTime.html#method-i-strftime) supports. Maybe do both?
