### ISSUE TITLE
Provide more robust filtering

### ISSUE THREAD

**Issue by itafroma** [itafroma/jekyll-archive#9]
Splitting off from #3, JAG should have more robust filtering now that you can have more than one archive. The idea is that `exclude` will become a nested mapping, with two keys—`categories` and `tags`—and will gain a complementary `include` nesting mapping with the same keys:

```yaml
archive:
    - layout: archive
      path: /blog/:year/:month/:day
      title: Blog archive - :year/:month/:day
      exclude:
          tags: ['hidden']
      include:
          categories: ['blog']
    - layout: archive
      path: /blog/:year/:month
      title: Blog archive - :year/:month
      exclude:
          tags: ['hidden']
      include:
          categories: ['blog']
    - layout: archive
      path: /blog/:year
      title: Blog archive - :year
      exclude:
          tags: ['hidden']
      include:
          categories: ['blog']
    - layout: archive
      path: /projects/:year
      title: Project archive - :year
      include:
          categories: ['projects']
```

The logic with the `include` and `exclude` keys would be the following:

- If `include` is missing, all posts will be included.
- If `include` is present, only posts matching the include criteria will be included.
- `exclude` is resolved after `include`.

For example, this would mean only posts in the `blog` category that do not have the `hidden` tag will be present in the archive type:

```yaml
include:
    categories: ['blog']
exclude:
    tags: ['hidden']
```
